### ISSUE TITLE
[Bug]: Unable to open Ice settings panel

### ISSUE THREAD

**Issue by alexistrn** [jordanbaird/Ice#371]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Hello there, thank's so much for this really useful and free tool ! 

It seems that there is an issue with the latest release. I'm on macOS 15.0 Sequoia (M2 pro chip) et now it's impossible to open Ice settings directly from the menubar (right click "Ice settings..."). On the click, nothing happen. I have to quit the app, then reload it and now I am able do access the settings panel. But after a computer startup, the problem reappear. Alternatively, when I go to launchpad after clicking on the "Ice settings..". menubar sub-menu, and when I click on the app icon from the launchpad, that's open the settings. I tried to deinstall the app with AppCleaner, but it seems to be the same. I installed Ice with homebrew.

Could you take a look at that ? 

### Steps to Reproduce

My config :
1. Set up the launch at login function
2. Enable automatically rehide
3. Enable show ice icon
4. Enable use ice bar
5. Use ellipsis Icon
6. None for tint
7. Border "1px" and shape kind "Split" with round corner
8. Enable the notch option
9. Try to change the menubar spacing, apply then reset it to normal behavior
10. Restart the computer then try to open the settings under the Ice icon and with a right click
11. Try to open the settings from the app icon in launchpad

### Ice Version

0.11.3

### macOS Version

15.0

**Comment by jordanbaird** [comment]
I believe I fixed the issue, but I can't reproduce it on either of my machines, so let me know once the next update comes out if it still happens.

**Comment by alexistrn** [comment]
Hello @jordanbaird. Yes, it seems to be fully solved in the 0.11.4, thank's a lot ! I really don't know why I had this issue but apparently I was nit the only one under macOS15 🤷‍♂️

**Comment by alexistrn** [comment]
> I believe I fixed the issue, but I can't reproduce it on either of my machines, so let me know once the next update comes out if it still happens.

Hello [@jordanbaird](https://github.com/jordanbaird). Yes, it seems to be fully solved in the 0.11.4, thank's a lot ! I really don't know why I had this issue but apparently I was nit the only one under macOS15 🤷‍♂️

**Comment by jordanbaird** [comment]
I just ran into the problem on startup. Weird. I'll reopen this.

**Comment by BrandonSmith** [comment]
Still seeing this on 0.11.5. For me, it seems to happen after a while of running Ice. If I quit and relaunch, things return to normal.

**Comment by alexistrn** [comment]
@jordanbaird Hello, sorry for the wrong information, after few startups, the problem reappear for me too..

**Comment by Stephen-Lon** [comment]
This has happened for me with at least the last two releases (0.11.4 & 0.11.5). When I install the new release it works (i.e., I can reveal the settings pane). However, after any reboot of my MacBook Pro I am unable to reveal the settings pane. I'm on macOS 15.0.

**Comment by j-peeters** [comment]
I have the same problem.
