### ISSUE TITLE
[Bug]: Menu Bar Layout BLANK (can't see any icons)

### ISSUE THREAD

**Issue by ranwoo1234** [jordanbaird/Ice#716]
### Search for Similar Reports

- [x] I have searched existing issues for similar reports

### Description

Updated Macbook Pro to Tahoe 26.0 and now I can't see any of the icons in Menu Bar Layout settings, no matter if I do "LIGHT"/"DARK"/"AUTO" appearance settings, it always looks like this:

<img width="911" height="633" alt="Image" src="https://github.com/user-attachments/assets/248ec232-a969-48e1-9141-8e1cfde91bc5" />

### Steps to Reproduce

Ice settings > Menu Bar Layout

### App Version

0.11.12

### macOS Version

26.0

**Comment by zdkcomeon** [comment]
me too

**Comment by andrewdiyi** [comment]
me too
<img width="1800" height="1250" alt="Image" src="https://github.com/user-attachments/assets/f88b3b38-fe98-4fa6-ae62-b022b7169074" />

**Comment by Xytronix** [comment]
<img width="1484" height="488" alt="Image" src="https://github.com/user-attachments/assets/425cb63c-470b-4da9-a99d-033c62e6e65e" />

Same issue upon updating to 26

**Comment by SchallerJe** [comment]
Try the beta under releases. Those issues have been fixed

**Comment by dinometeu-dev** [comment]
I have the same issue on the stable version of MacOs 26. The App version: 0.11.12

<img width="2412" height="1550" alt="Image" src="https://github.com/user-attachments/assets/6945c29d-8e05-4607-bcd9-2f220f905c55" />
<img width="1528" height="1966" alt="Image" src="https://github.com/user-attachments/assets/f093383e-959c-4c9d-9f08-af0d7378580e" />

**Comment by raulfdm** [comment]
Can confirm that the version [`Ice 0.11.13 (macOS Tahoe Beta 2)`](https://github.com/jordanbaird/Ice/releases/tag/0.11.13-dev.2) has fixed this issue.


## Update

Maybe I did a bold statement that it fixed for everyone so I'm here to reiterate that it worked for **me**. Here's my settings:

<img width="1924" height="1328" alt="Image" src="https://github.com/user-attachments/assets/132021a8-3435-478b-8d9e-47c727018966" />

<img width="1182" height="599" alt="Image" src="https://github.com/user-attachments/assets/cfd18aa0-c82f-4a76-837e-76a4dfdf3029" />

**Comment by Zirmeiche** [comment]
I have totally removed the previous beta Version, restarted the Mac and  installed [Ice 0.11.13 (macOS Tahoe Beta 2)]. Unfortunately I still have the same problem with version [Ice 0.11.13 (macOS Tahoe Beta 2)]. The issue is NOT fixed on my Mac Tahoe 26.1 Beta.

**Comment by andrewdiyi** [comment]
> me too <img alt="Image" width="1800" height="1250" src="https://private-user-images.githubusercontent.com/44893972/494301505-f88b3b38-fe98-4fa6-ae62-b022b7169074.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTkwMjMxMzMsIm5iZiI6MTc1OTAyMjgzMywicGF0aCI6Ii80NDg5Mzk3Mi80OTQzMDE1MDUtZjg4YjNiMzgtZmU5OC00ZmE2LWFlNjItYjAyMmI3MTY5MDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTI4VDAxMjcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0YWQyZGUzZjNjOWU5ODEzZGVlMGU2YzJhMDNkMmRiYjhlMzYwM2VkODBhZmRmZGM5YzIwN2ZmZjM5MmJiNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.enQuWOF5zPly5XWQvWm2QU_U_GrioeFWTdUy3mwD60M">

I am using macOS 26.0 stable release. After installing [Ice 0.11.13-dev.2], the issue was resolved.

<img width="1800" height="1250" alt="Image" src="https://github.com/user-attachments/assets/a098a779-817d-4896-a888-56a54af7d64d" />

**Comment by karamfil** [comment]
The issue is still present for me with 0.11.13-dev.2

<img width="538" height="223" alt="Image" src="https://github.com/user-attachments/assets/be38e075-ce9c-4ace-9b20-a359395c9927" />

<img width="135" height="21" alt="Image" src="https://github.com/user-attachments/assets/29587f77-055b-4920-af0f-a5ec295aefdd" />

<img width="801" height="333" alt="Image" src="https://github.com/user-attachments/assets/e2c683de-6620-4670-8ec6-1a5acf617db3" />

**Comment by RobMcRob24** [comment]
For me also the issue is still there with 26.0.1 and 11.13-dev.2

**Comment by jasondail** [comment]
Same issue for me as the others. Additionally, when I click on the Ice icon in the menu bar, it crashes - confirmed in Activity Monitor the program is killed when clicking on the icon. Clicking/hovering on empty space does nothing (doesn't show hidden icons).

Reinstalled 11.12 and same.

Installed 11.12-dev2 and so far so good - clicking on ice icon shows hidden icons, clicking on empty space shows icons.
Tried all of this on 26.0.1.

**Comment by atarx** [comment]
Same error with Tahoe 26.0.1 (25A362)

<img width="613" height="277" alt="Image" src="https://github.com/user-attachments/assets/666fcd23-6ab9-4625-ac90-97b61b932d91" />

<img width="879" height="476" alt="Image" src="https://github.com/user-attachments/assets/fed4a8b4-e641-4a5a-a38b-20a543a9c3ae" />

**Comment by zakariachahbar** [comment]
Same issue for me. Raised it in #711

**Comment by ivoidcat** [comment]
I tried dev2, but it still doesn't show up on my computer. I uninstalled and reinstalled it, but it didn't work.

**Comment by ysl2** [comment]
> I tried dev2, but it still doesn't show up on my computer. I uninstalled and reinstalled it, but it didn't work.

+1, dev2 can't work as same.

**Comment by anobjectn** [comment]
I have updated my Tahoe and ICE, I have double checked app permissions. **What has helped me is reading the screen and it DOES read "Use Command + Dragging" in the menu bar.... yes its true. At least now I can place the icons in the proper position while this bug is worked out!**

**Comment by karamfil** [comment]
Has anyone found a fix for this?

**Comment by anobjectn** [comment]
Command + Dragging the icons in place helped me have the right icons in the shown vs hidden groups and the order I prefer.

**Comment by jdanbrown** [comment]
As a temporary workaround (without having to change `Displays have separate spaces`), @stonerl shared a debug build of Ice.app that includes a fix from their open PR:
- Debug build: https://github.com/jordanbaird/Ice/issues/711#issuecomment-3712564054
- Open PR: https://github.com/jordanbaird/Ice/pull/839

**Comment by Pranav-Karra-3301** [comment]
Root caused this: the Tahoe menu bar window is fully transparent, so Ice's average color capture ends up dividing by zero and produces a NaN color. That renders the layout rows solid white, and it also forces the "Unable to display menu bar items" fallback text to white, so the pane looks completely empty instead of showing the error. Fix is up in #972. In the meantime the 0.11.13-dev.2 beta avoids the white background, though on 26.4 and later you may also need the fix from #922.

**Comment by detunized** [comment]
<img width="1012" height="737" alt="Image" src="https://github.com/user-attachments/assets/246e5ef8-97fe-43a9-a3c1-807d4a0ec628" />

<img width="392" height="599" alt="Image" src="https://github.com/user-attachments/assets/aaff4003-9432-467c-ba44-6739470fb48d" />

Same for me
