### ISSUE TITLE
[Bug]: Cannot toggle menubar or access Ice menu on non-main display

### ISSUE THREAD

**Issue by unikitty37** [jordanbaird/Ice#72]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

When using multiple displays, clicking in the empty part of the menubar to toggle the hidden section only works on the main display; on the other displays nothing happens.

The same happens when right-clicking: the menu only appears when using the main display.

This might be related to the way macOS assigns the displays to ports: on my Mac Studio, I have the display on the left connected to HDMI, and the display on the right connected via a USB-C – DisplayPort dongle. This seems to cause the display on the left to have negative x-coordinates, which confuses some application.

### Steps to Reproduce

1. Set up macOS with multiple displays
2. Physically arrange the displays so that the left-hand display has negative x-coordinates
3. In the Displays settings, drag that display to be to the left of the other one
4. Make the right-hand display the main display
5. Launch Ice
6. Try clicking or right-clicking in the empty space in the menu bar on the left-hand screen

### Ice Version

0.8.0

### macOS Version

macOS 14.5 (23F79)

### Screenshots

![image](https://github.com/jordanbaird/Ice/assets/139183/5099b5a9-5bb1-495b-8999-cabfb9883d9d)

**Comment by jordanbaird** [comment]
This is a bug in 0.8.0. It has been fixed on `main`. I'll be putting out a new release soon with the fix.

**Comment by unikitty37** [comment]
@jordanbaird Thanks — I've just installed 0.9.0 and it's still not quite right.

After launching Ice, clicking the secondary display's menubar doesn't unhide the hidden items. If I unhide them from the main display's menubar and then re-hide them from that display, I can now unhide the hidden items by clicking the secondary display's menubar, but hiding still only works from the main display.

Right-clicking the Ice icon on the secondary display works consistently, but it's a bit of a pain :)

**Comment by sleepymalc** [comment]
@jordanbaird I also encountered the same issue. 0.9.0 doesn't seem to solve the issue yet.
